name: Expose Proxy via Pinggy

on:
  workflow_dispatch:

jobs:
  tunnel:
    runs-on: ubuntu-latest

    steps:
      - name: Install Squid
        run: |
          sudo apt-get update
          sudo apt-get install -y squid
          sudo truncate -s 0 /etc/squid/squid.conf
          echo "http_port 3128" | sudo tee -a /etc/squid/squid.conf
          echo "http_access allow all" | sudo tee -a /etc/squid/squid.conf
          sudo service squid restart

      - name: Start Pinggy Tunnel
        run: |
          ssh -p 443 -R0:localhost:3128 tcp@a.pinggy.io > tunnel.log 2>&1 &
          sleep 10
          echo "====== PROXY ======"
          cat tunnel.log
          echo "==================="
          sleep 21600
